name: Java CI with Playwright

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Playwright system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libavif16 \
            libmanette-0.2-0 \
            gstreamer1.0-libav \
            libvpx9 \
            libopus0 \
            libwoff1 \
            libharfbuzz-icu0 \
            libgles2

      - name: Run Playwright install-deps
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install-deps"

      - name: Run tests with headless mode
        run: mvn tes -Dplaywright.headless=true